name: newschooluganda
description: App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 0.0.1+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:

  authentication_repository:
    path: packages/authentication_repository
  flutter:
    sdk: flutter

  formz: ^0.4.1
  google_fonts: ^2.1.0
  flow_builder: ^0.0.6
  font_awesome_flutter: ^9.2.0
  very_good_analysis: ^2.4.0
  form_inputs:
    path: packages/form_inputs

  meta: ^1.7.0
  bloc: ^8.0.2
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1

dev_dependencies:
  bloc_test: ^9.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/

#   fonts:
#     - family: Schyler
#       fonts:
#         - asset: fonts/Schyler-Regular.ttf
#         - asset: fonts/Schyler-Italic.ttf
#           style: italic
#     - family: Trajan Pro
#       fonts:
#         - asset: fonts/TrajanPro.ttf
#         - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700
